eno = parseInt(prompt("Enter Employee Id:"));
ename=prompt("Enter Employee Name:")
esal=parseInt(prompt("Enter Employee Salary:"))
epf=parseInt(prompt("Enter Employee PF:"))
egrade=prompt("Enter Employee Grade:")
console.log("----------------------------------------")
console.log("Employee Number=",eno)
console.log("Employee Name=",ename)
console.log("Employee Salary=",esal)
console.log("Provident Fund=",epf)
console.log("Employee Grade=",egrade)
console.log("----------------------------------------")